name: After server responds
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      with: # Configura o segredo como uma entrada
        CYPRESS_KEY: ${{ secrets.CYPRESS_KEY }}
        env:
          CYPRESS_KEY: ${{ secrets.CYPRESS_KEY }}
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress run
        uses: cypress-io/github-action@v1
      - name: GitHub Action for Yarn + Cypress
        uses: KingScooty/actions-yarn-cy@1.0.0
        with:
          start: yarn start
          # quote the url to be safe against YML parsing surprises
          wait-on: 'http://localhost:3000'
