name: After server responds
on: [push, pull_request, pull_request_review]
jobs:
  cypress-run:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          # quote the url to be safe against YML parsing surprises
          start: yarn start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
